### ISSUE TITLE
Bug in api 5

### ISSUE THREAD

**Issue by MateusBlackyOFC** [HBIDamian/TimeCommander#8]
![image](https://github.com/HBIDamian/TimeCommander/assets/89048733/06a5eb05-0543-4100-b0e8-a967e8e02d77)

**Comment by HBIDamian** [comment]
I'll work on this tonight (in about 9 to 11 hours). 

Cheers. :)

**Comment by HBIDamian** [comment]
@MateusBlackyOFC Just out if interest, use the `/version` command. 
And also provide me steps to reproduce the error? I'm not getting any error whilst testing it.

**Comment by HBIDamian** [comment]
Actually, I had a bit of time. I've submitted it to Poggit. 
Until then, you can either compile it yourself or head on over to https://poggit.pmmp.io/ci/HBIDamian/TimeCommander/TimeCommander
